Update _workgroups.xml for UK Core
ryma2fhir/JIRA-Spec-Artifacts pull request #1
Opened 2024-11-22 11:04 UTC by ryma2fhir

2024-12-09 15:32 UTC, ryma2fhir commented
Currently action fails as there needs to be a giturl which starts with github.com/HL7
Issue added to existing https://github.com/HL7/JIRA-Spec-Artifacts/issues/920

2024-12-12 16:35 UTC, lmckenzi commented
The work group shouldn't be "uk core".  The work group would correspond to the affiliate and would be used for *all* HL7 UK publications submitted through the HL7 international ballot process

2024-12-28 11:56 UTC, vickyjaiswal0308 commented on xml/_workgroups.xml
Don't we have to give a webcode?

2024-12-28 12:01 UTC, vickyjaiswal0308 commented on xml/FHIR-uk-core.xml
I think we have to mention the workgroup with each and every artifact

2025-01-03 04:50 UTC, lmckenzi requested changes
Attribute needs to be gitUrl, not gitUri.  (Try to use a schema-validating editor when changing the files.)

2025-01-07 12:01 UTC, ryma2fhir commented on xml/FHIR-uk-core.xml
No, from https://confluence.hl7.org/display/HL7/Configuring+Specification+Feedback

> workgroup: This is the work group generally responsible for maintaining the page.  It only needs to be specified if different from the work group generally responsible for the specification overall (i.e. where different artifacts and pages within the specification fall under the responsibility of different work groups).

2025-01-07 12:07 UTC, ryma2fhir commented on xml/_workgroups.xml
From https://confluence.hl7.org/display/HL7/Configuring+Specification+Feedback
`webcode: the 'code' for the work group's home-page (i.e. the part of the URL following [http://hl7.org/Special/committees/](http://www.hl7.org/Special/committees/) when locating the work group's home page).  This is used when helping to match ImplementationGuides to their work group using the ImplementationGuide.contact`

We don't need a ImplementationGuide instance, as it is not needed for Simplifier to work. I've checked and not all work groups have a webcode either so this is not mandatory

2025-01-07 16:51 UTC, lmckenzi commented
I've updated the validation scripts to support the UK Git location.  Try merging base and see if that resolves the validation issues.

2025-01-21 15:05 UTC, ryma2fhir commented
Reviewed by Vicky and Jade

2025-01-21 15:05 UTC, merged

2025-01-21 15:16 UTC, ryma2fhir commented
> Try merging base and see if that resolves the validation issues.

Hi @lmckenzi I tried merging base and I still get the error within the github action. 

I've merged this PR into my master branch and created a new PR https://github.com/HL7/JIRA-Spec-Artifacts/pull/1175